version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - database-data:/data/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: proposal_model
      MYSQL_HOST: localhost
    restart: always

volumes:
  database-data: